name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          server-username: GITHUB_USER_REF
          server-password: GITHUB_TOKEN_REF

      - name: Add execute permissions to script
        run: chmod +x ./check-version.sh

      - name: Check if version exists
        id: chkvrsn
        run: ./check-version.sh
        env:
          PAT: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
          USER: ${{ secrets.PACKAGE_ACCESS_USER }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          GITHUB_USER_REF: ${{ secrets.PACKAGE_ACCESS_USER }}
          GITHUB_TOKEN_REF: ${{ secrets.PACKAGE_ACCESS_TOKEN }}

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
        if: ${{ steps.chkvrsn.outputs.exists == 'false' }}
